// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_Ph0nTlIzaYRauT8vXR8iLqNDxX5qKDA',
    appId: '1:843319747060:web:d2faefa21a1f2f84df19a1',
    messagingSenderId: '843319747060',
    projectId: 'arq-mpro-ject',
    authDomain: 'arq-mpro-ject.firebaseapp.com',
    storageBucket: 'arq-mpro-ject.firebasestorage.app',
    measurementId: 'G-4F2TL8TY6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA27Jp5XIxKKIMgEo3jYYnszdT5XaTyejc',
    appId: '1:843319747060:android:b6b09494dd630c30df19a1',
    messagingSenderId: '843319747060',
    projectId: 'arq-mpro-ject',
    storageBucket: 'arq-mpro-ject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcnEeAAKELMb8L5VRotHsqHr2TeGgls0w',
    appId: '1:843319747060:ios:0647bc57e241a6dfdf19a1',
    messagingSenderId: '843319747060',
    projectId: 'arq-mpro-ject',
    storageBucket: 'arq-mpro-ject.firebasestorage.app',
    iosBundleId: 'com.example.flutterDemoppkdAriq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcnEeAAKELMb8L5VRotHsqHr2TeGgls0w',
    appId: '1:843319747060:ios:0647bc57e241a6dfdf19a1',
    messagingSenderId: '843319747060',
    projectId: 'arq-mpro-ject',
    storageBucket: 'arq-mpro-ject.firebasestorage.app',
    iosBundleId: 'com.example.flutterDemoppkdAriq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_Ph0nTlIzaYRauT8vXR8iLqNDxX5qKDA',
    appId: '1:843319747060:web:8e890998fcbfd689df19a1',
    messagingSenderId: '843319747060',
    projectId: 'arq-mpro-ject',
    authDomain: 'arq-mpro-ject.firebaseapp.com',
    storageBucket: 'arq-mpro-ject.firebasestorage.app',
    measurementId: 'G-QFJPK6HGGS',
  );
}
